# -*- coding: utf-8 -*-
"""Ex1_Python_Ming.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SB4HfN7H6ZAhV5ElMBj_8PvwRiA-nzOc

<a href="https://colab.research.google.com/github/myothida/PythonProgramming/blob/main/Ex1_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction

This section introduces the Python Programming uisng Colab. Follow the instructions and complete the exercises.

# Ex 1 : Check Version

Using the below cell, Import the required library and check the version of the python in your environment.
"""

import sys
sys.version

"""# Ex2 : Convert Currency.

Write a program that asks the user for the amount in usd and converts it to British pounds. The exchange rate is from usd to BP is given as 0.82
"""

usd_amount = input ("Enter the amount in USD: ")
bp_amount = int(usd_amount) *0.82
print("{} usd is equivalent to {} british pound".format(usd_amount, bp_amount))

"""# Ex 3: Temperature Converter

Write a program that convert temperature in Feranhite to celsius.
"""

f = input ("Enter the temperature in Feranhite: ")
c = ((int(f)-32) * 5/9)
print("{}°F is equivalent to {}°C ".format(f, c))

"""# Ex 4: Daily Maths

You are working in a retail shop. Write a program that computes the total cost for a customer that bought 3 differnt types of fruits : apple, orange, mango. Ask the user to enter the quantity and price for each type.
"""

apple_q = input("Enter the quantity of apples: ")
apple_p = input("Enter the price per apple: ")

orange_q = input("Enter the quantity of oranges: ")
orange_p = input("Enter the price per orange: ")

mango_q = input("Enter the quantity of mangoes: ")
mango_p = input("Enter the price per mango: ")

apple_c = int(apple_q) * int(apple_p)
orange_c = int(orange_q) * int(orange_p)
mango_c = int(mango_q) * int(mango_p)

total_c = apple_c + orange_c + mango_c

print("total cost is equivalent to " + str(total_c))

"""# Ex 5 : Greeting

Write a program to greet the customer who provides the user name. Your program should ask the name of the customer and print "Hello + customer name"
"""

customer_n = input ("Enter the name of the customer: ")
print("Hello, " + customer_n)